---
- name: playbook to install git, maven, tree, java, elinks in all target nodes
  hosts: valid
  become: true
  gather_facts: false
  tasks:
   - name: create a user account
     user:
      name: Ganga
      password: 11223344
      home: /home/Ganga
      shell: /bin/bash
     register: output
   - name: print the output
     debug: 
      var: output
   - name:  change the password if the account was already present
     user:
      name: Ganga
      password: 00001111
     when:
      output.changed== false
...
