---
- name: playbook to install git in all target nodes
  hosts: all
  become: true
  gather_facts: false
  tasks:
   - name: install git
     apt:
      name: git
      state: present
      update_cache: yes
...
